# ============================================================
# Spatial GP-IRT (binary 2PL with anisotropic GP difficulty)
# R Package Functions
# ============================================================

# -------------------------
# Internal Helper functions
# -------------------------
make_sqdist_mats <- function(coords) {
  stopifnot(is.matrix(coords), ncol(coords) == 2)
  sqdist1 <- outer(coords[, 1], coords[, 1], "-")^2
  sqdist2 <- outer(coords[, 2], coords[, 2], "-")^2
  list(sqdist1 = sqdist1, sqdist2 = sqdist2)
}

make_anisotropic_kernel <- function(coords, sigma_gp, ell1, ell2, sigma_nug) {
  d <- make_sqdist_mats(coords)
  K <- sigma_gp^2 * exp(-0.5 * (d$sqdist1 / ell1^2 + d$sqdist2 / ell2^2))
  diag(K) <- diag(K) + sigma_nug^2 + 1e-8
  K
}

# -------------------------
# Exported functions
# -------------------------

#' Simulate data from a Spatial GP-IRT model
#'
#' @description Simulates binary responses from a 2PL Item Response Theory model
#' where item difficulties are drawn from an anisotropic Gaussian Process over a 2D spatial domain.
#'
#' @param I Integer. Number of respondents. Default is 200.
#' @param J Integer. Number of items. Default is 50.
#' @param p Integer. Number of covariates. Default is 1.
#' @param sigma_theta_true Numeric. Standard deviation of respondent abilities. Default is 1.0.
#' @param sigma_alpha_true Numeric. Standard deviation of log item discriminations. Default is 0.35.
#' @param sigma_gp_true Numeric. Marginal standard deviation of the GP. Default is 1.0.
#' @param sigma_nug_true Numeric. Nugget standard deviation for the GP. Default is 0.15.
#' @param ell_true Numeric vector of length 2. Length-scale parameters for the anisotropic GP. Default is c(0.20, 0.45).
#' @param gamma_true Numeric vector. True covariate effects. Default is 0.50.
#' @param seed Integer. Random seed for reproducibility. Default is 1234.
#'
#' @return A list containing two elements: `stan_data` (formatted for CmdStanR) and `truth` (the true simulated parameters).
#' @export
simulate_sgp_irt_binary <- function(
    I = 200,
    J = 50,
    p = 1,
    sigma_theta_true = 1.0,
    sigma_alpha_true = 0.35,
    sigma_gp_true = 1.0,
    sigma_nug_true = 0.15,
    ell_true = c(0.20, 0.45),
    gamma_true = 0.50,
    seed = 1234
) {
  stopifnot(length(ell_true) == 2)
  set.seed(seed)

  coords <- cbind(runif(J), runif(J))

  K_true <- make_anisotropic_kernel(
    coords = coords,
    sigma_gp = sigma_gp_true,
    ell1 = ell_true[1],
    ell2 = ell_true[2],
    sigma_nug = sigma_nug_true
  )

  beta_true <- as.numeric(MASS::mvrnorm(1, mu = rep(0, J), Sigma = K_true))
  beta_true <- beta_true - mean(beta_true)

  theta_true <- rnorm(I, mean = 0, sd = sigma_theta_true)
  alpha_true <- exp(rnorm(J, mean = 0, sd = sigma_alpha_true))

  N <- I * J
  subj_id <- rep(seq_len(I), each = J)
  item_id <- rep(seq_len(J), times = I)
  X <- matrix(runif(N * p, min = -1, max = 1), nrow = N, ncol = p)

  if (length(gamma_true) == 1 && p > 1) {
    gamma_true <- rep(gamma_true, p)
  }
  stopifnot(length(gamma_true) == p)

  eta <- alpha_true[item_id] * theta_true[subj_id] - beta_true[item_id] + as.numeric(X %*% gamma_true)
  prob <- plogis(eta)
  y <- rbinom(N, size = 1, prob = prob)

  sqdist <- make_sqdist_mats(coords)

  stan_data <- list(
    N = N,
    I = I,
    J = J,
    y = y,
    subj_id = subj_id,
    item_id = item_id,
    p = p,
    X = X,
    sqdist1 = sqdist$sqdist1,
    sqdist2 = sqdist$sqdist2,
    grainsize = 1
  )

  truth <- list(
    theta = theta_true,
    alpha = alpha_true,
    beta = beta_true,
    gamma = gamma_true,
    coords = coords,
    prob = prob,
    y = y,
    subj_id = subj_id,
    item_id = item_id,
    X = X
  )

  list(stan_data = stan_data, truth = truth)
}

#' Fit the Spatial GP-IRT model using CmdStanR
#'
#' @description Compiles and samples from the spatial GP-IRT model using Hamiltonian Monte Carlo.
#'
#' @param stan_data List. Data object generated by \code{\link{simulate_sgp_irt_binary}}.
#' @param stan_file Character. Path to the compiled Stan file. Defaults to the package's internal file.
#' @param chains Integer. Number of MCMC chains. Default is 4.
#' @param parallel_chains Integer. Number of chains to run in parallel. Default is 4.
#' @param threads_per_chain Integer. Number of CPU threads to allocate per chain for reduce_sum. Default is 2.
#' @param iter_warmup Integer. Number of warmup iterations per chain. Default is 1000.
#' @param iter_sampling Integer. Number of post-warmup sampling iterations per chain. Default is 1000.
#' @param seed Integer. Random seed for CmdStan. Default is 1234.
#' @param adapt_delta Numeric. Target average acceptance probability. Default is 0.95.
#' @param max_treedepth Integer. Maximum tree depth for the NUTS sampler. Default is 12.
#'
#' @return A list containing the compiled `model` object and the fitted `fit` object.
#' @export
fit_sgp_irt_binary <- function(
    stan_data,
    stan_file = NULL,
    chains = 4,
    parallel_chains = 4,
    threads_per_chain = 2,
    iter_warmup = 1000,
    iter_sampling = 1000,
    seed = 1234,
    adapt_delta = 0.95,
    max_treedepth = 12
) {

  if (is.null(stan_file)) {
    stan_file <- system.file("stan", "sgp_irt_binary_cmdstanr.stan", package = "SpatialGPIRT")
    if (stan_file == "") stop("Stan file not found in package installation.")
  }

  mod <- cmdstanr::cmdstan_model(
    stan_file,
    cpp_options = list(stan_threads = TRUE)
  )

  fit <- mod$sample(
    data = stan_data,
    seed = seed,
    chains = chains,
    parallel_chains = parallel_chains,
    threads_per_chain = threads_per_chain,
    iter_warmup = iter_warmup,
    iter_sampling = iter_sampling,
    refresh = 100,
    adapt_delta = adapt_delta,
    max_treedepth = max_treedepth
  )

  list(model = mod, fit = fit)
}

#' Extract posterior means from the fitted model
#'
#' @description Calculates the column means for the primary parameters (theta, alpha, beta, gamma)
#' from the posterior draws.
#'
#' @param fit_obj List. The output object from \code{\link{fit_sgp_irt_binary}}.
#'
#' @return A list of numeric vectors containing the posterior means for each parameter.
#' @export
posterior_means_from_fit <- function(fit_obj) {
  fit <- fit_obj$fit
  list(
    theta = colMeans(fit$draws(variables = "theta", format = "matrix")),
    alpha = colMeans(fit$draws(variables = "alpha", format = "matrix")),
    beta  = colMeans(fit$draws(variables = "beta", format = "matrix")),
    gamma = colMeans(fit$draws(variables = "gamma", format = "matrix"))
  )
}

#' Compute parameter recovery metrics
#'
#' @description Calculates the Root Mean Square Error (RMSE) between the true simulated parameters
#' and the estimated posterior means.
#'
#' @param post_means List. Posterior means generated by \code{\link{posterior_means_from_fit}}.
#' @param truth List. True parameter values generated by \code{\link{simulate_sgp_irt_binary}}.
#'
#' @return A list containing the RMSE for theta, alpha, beta, and gamma.
#' @export
compute_recovery_metrics <- function(post_means, truth) {
  list(
    rmse_theta = sqrt(mean((post_means$theta - truth$theta)^2)),
    rmse_alpha = sqrt(mean((post_means$alpha - truth$alpha)^2)),
    rmse_beta  = sqrt(mean((post_means$beta  - truth$beta)^2)),
    rmse_gamma = sqrt(mean((post_means$gamma - truth$gamma)^2))
  )
}

#' Compute posterior mean predictive probabilities
#'
#' @description Calculates the expected probability of a positive response for each observation
#' by integrating over the posterior distribution of the model parameters.
#'
#' @param fit_obj List. The output object from \code{\link{fit_sgp_irt_binary}}.
#' @param truth List. True dataset object generated by \code{\link{simulate_sgp_irt_binary}}.
#' @param ndraws Integer. Number of posterior draws to use for the calculation. Default is 250.
#'
#' @return A numeric vector of length N containing the posterior mean probability of y = 1.
#' @export
posterior_mean_probabilities <- function(fit_obj, truth, ndraws = 250) {
  fit <- fit_obj$fit

  theta_draws <- fit$draws(variables = "theta", format = "matrix")
  alpha_draws <- fit$draws(variables = "alpha", format = "matrix")
  beta_draws  <- fit$draws(variables = "beta", format = "matrix")
  gamma_draws <- fit$draws(variables = "gamma", format = "matrix")

  n_total <- nrow(theta_draws)
  keep <- seq_len(min(ndraws, n_total))

  N <- length(truth$y)
  prob_mat <- matrix(NA_real_, nrow = N, ncol = length(keep))

  for (s_idx in seq_along(keep)) {
    s <- keep[s_idx]
    eta_s <- alpha_draws[s, truth$item_id] * theta_draws[s, truth$subj_id] -
      beta_draws[s, truth$item_id] + as.numeric(truth$X %*% gamma_draws[s, ])
    prob_mat[, s_idx] <- plogis(eta_s)
  }

  rowMeans(prob_mat)
}
